### ISSUE TITLE
Fails under python 3.5 (probably all 3.x)

### ISSUE THREAD

**Issue by vlcinsky** [wolever/autorepr#4]
`autorepr` caused failures of my code under python 3.5 as it tries to use function `unicode`.

My PR #3 adds tox driven tests to simplify testing under multiple python versions. There are still some failing cases, which I did not manage fixing in some simple manner.

The package also does not declare, what python versions are supported.

**Comment by wolever** [comment]
Ahh, thanks! I'll get that merged and proper 3.x support out asap!

**Comment by vlcinsky** [comment]
Nice and really quick work - awesome.

I pulled the latest version, run your tests and all works fine (my environment provides python version 2.7 and 3.5). Thanks a lot (looking forward to release).
